apiVersion: v1
kind: ConfigMap
metadata:
  name: loan-service-config
  namespace: library-system
data:
  DB_HOST: "postgres"
  DB_NAME: "loan_db"
  EUREKA_HOST: "discovery-server"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  namespace: library-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      containers:
        - name: loan-service
          image: library/loan-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: loan-service-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: loan-service
  namespace: library-system
spec:
  selector:
    app: loan-service
  ports:
    - port: 8083
      targetPort: 8083
